[package]
name = "remote_logger"
version = "0.1.0"
edition = "2018"

[features]
default = ["chrono", "thiserror"]
len-u128 = []

[dependencies]
chrono = { version = "0.4.19", optional = true }
log = { version = "0.4.14", features = ["std"] }
thiserror = { version = "1.0.26", optional = true }