[package]
name = "remote_logger"
version = "0.1.0"
edition = "2018"

[features]
default = ["chrono"]

[dependencies]
log = { version = "0.4.14", features = ["std"] }
chrono = { version = "0.4.19", optional = true }